import type { ToolDefinition } from '../toolTypes.js';
import { GitHubBranchService } from './githubBranchService.js';
import { GitHubPullRequestService } from './githubPullRequestService.js';

export function createCompanyGitHubTool(
  branches: GitHubBranchService,
  pullRequests: GitHubPullRequestService
): ToolDefinition<
  { action: 'create_branch' | 'create_pr' | 'get_pr_status' | 'request_review' | 'approve_merge'; projectId: string; repo: string; branchName?: string; baseBranch?: string; title?: string; body?: string; prId?: string; agentId?: string },
  unknown
> {
  return {
    name: 'github.company',
    description: 'Create branches, PRs, request reviews, inspect status, and merge only after approval.',
    inputSchema: 'GitHub company action',
    outputSchema: 'GitHub action result',
    permissionLevel: 'external',
    approvalRequired: false,
    async execute(input) {
      if (input.action === 'create_branch') {
        return branches.create({
          projectId: input.projectId,
          repo: input.repo,
          branchName: input.branchName || `agency/${input.projectId}`,
          baseBranch: input.baseBranch || 'main',
          createdByAgentId: input.agentId || 'builder'
        });
      }
      if (input.action === 'create_pr') {
        return pullRequests.create({
          projectId: input.projectId,
          repo: input.repo,
          branchName: input.branchName || `agency/${input.projectId}`,
          title: input.title || 'Agency build update',
          body: input.body || 'Generated by the agency workflow.',
          createdByAgentId: input.agentId || 'builder'
        });
      }
      if (input.action === 'get_pr_status' && input.prId) return pullRequests.get(input.prId);
      if (input.action === 'request_review' && input.prId) return pullRequests.update(input.prId, { status: 'review_requested' });
      if (input.action === 'approve_merge' && input.prId) throw new Error('PR merge requires approval through approvalService');
      throw new Error(`Unsupported GitHub action: ${input.action}`);
    }
  };
}
