export const reusableWebsiteSections = {
  HeaderSection: 'navbar bg-base-100/85 backdrop-blur border-b border-base-300',
  HeroSection: 'hero min-h-[calc(100vh-4.5rem)]',
  PropertySearchHero: 'image-led hero with glass search panel, filter chips, and proof metrics',
  FullBleedTravelHero: 'full-bleed media hero with headline pill highlight, facility chips, and concierge CTA',
  CenteredCarouselHero: 'centered SaaS/product hero with highlighted words and rounded media carousel',
  KineticProductHero: 'dark cinematic product/persona stage with preview card and metric rail',
  InteriorSplitHero: 'split image and warm editorial panel for interiors, venues, and lifestyle brands',
  ArchitectureStripHero: 'minimal oversized typography with panoramic project media strip',
  LuxuryMediaHero: 'full-bleed editorial property or luxury hero with protected overlay copy, stats, and private enquiry actions',
  EditorialStatementSection: 'large serif positioning statement paired with concise supporting copy',
  AssetPortfolioGrid: 'asymmetric media portfolio for property, products, destinations, and case studies',
  LuxuryServiceRows: 'numbered service comparison rows with restrained editorial interaction',
  CinematicStatementSection: 'full-width media statement for brand principles and point-of-view content',
  ImagePrinciplesSplit: 'image-led split layout with reusable values and decision principles',
  AudienceEditorialGrid: 'repeated audience or use-case grid with strong editorial hierarchy',
  ProcessTimeline: 'structured acquisition, concierge, or project process timeline',
  PrivateAccessCta: 'high-intent private viewing or enquiry call to action',
  PrivateInquiryForm: 'accessible enquiry form for viewings, consultations, and private client requests',
  ServicesSection: 'grid md:grid-cols-3 gap-6 card-driven service comparison',
  TestimonialsSection: 'grid md:grid-cols-3 gap-6 customer proof cards',
  PricingSection: 'grid md:grid-cols-3 gap-6 price cards',
  FaqSection: 'space-y-3 DaisyUI collapse components',
  ContactSection: 'card bg-base-100 shadow-xl form controls',
  GallerySection: 'responsive image gallery with local placeholder assets',
  CtaSection: 'hero bg-primary text-primary-content rounded-box',
  FooterSection: 'footer footer-horizontal footer-center'
} as const;
